### ISSUE TITLE
Spark RSR SLO graph should have a target value

### ISSUE THREAD

**Issue by BigLep** [davidgasquez/filecoin-storage-providers-market#6]
On our SP detail page when we're rendering the Spark RSR SLI, we should also show a target horizontal value.  

https://filecoin-project.github.io/filecoin-storage-providers-market/provider/f03088052

<img width="912" alt="image" src="https://github.com/user-attachments/assets/c6c470fd-d68b-48b3-b41f-d9be0dbd23fe">

**Comment by davidgasquez** [comment]
Let's go with 90% for now!
